import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header, Footer } from "@belajar/components";
import { StartFieldCanvas } from "@belajar/components";
import StarfieldCanvas from "components/StartFieldCanvas";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <StarfieldCanvas />
        {/* <Header /> */}
        {/* <main style={{ position: "relative", zIndex: 1 }}>{children}</main> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
